create database health_care;
use health_care;

select * from bills ;
select * from departments ;
select * from doctors ;
select * from medicines ;
select * from patients ;
select * from treatments;

  #   BASIC QUESTIONS::

# 1. Find total number of patients admitted in the hospital.

select count(patient_id) 
as total_patients 
from patients;

# 2. Calculate Male and Female patients count in hospital.

select gender,count(gender)
 from patients
group by gender;

# 3. Find total number of departments available in the hospital.

select count(department_name)
 as total_dept 
 from departments;

# 4. Identify which disease is most common among all patients.

select disease 
from patients 
order by disease desc limit 1;

# 5.Calculate total revenue generated by the hospital.

select sum(total_amount)
 as total_revenue 
 from bills;
 
 # INTERMEDIATE QUESTIONS::
 
# 6. Calculate number of patients per each department.

select count(p.patient_id) as no_of_patient,d.department_name 
from patients p 
join departments d on p.department_id=d.department_id 
group by department_name;

# 7. Find average bill amount per doctor based on their patient bills.

select d.doctor_name, avg(b.total_amount) as avg_bill,patient_name
from bills b 
join patients p on b.patient_id=p.patient_id 
join doctors d on d.doctor_id = p.patient_id
group by  doctor_name ,patient_name
order by avg_bill desc;

# 8. Identify the most prescribed medicine in the hospital.

select max(medicine_name) from medicines order by medicine_name desc;

select m.medicine_name, count(medicine_name) as freq 
from medicines m 
join treatments t on m.medicine_id = t.medicine_id
group by medicine_name
order by medicine_name desc limit 1;

# 9. Find top 3 departments generating the highest revenue.

select d.department_name, sum(total_amount) as total_revenue 
from bills b 
join patients p on p.patient_id = b.patient_id 
join departments d on p.department_id=d.department_id
group by department_name 
order by total_revenue desc 
limit 3;

# 10. Calculate total quantity of medicines consumed in hospital treatments.

select m.medicine_name,sum(quantity) as total_quantity
from treatments t 
join medicines m on t.medicine_id=m.medicine_id
group by medicine_name; 

SELECT SUM(quantity) AS total_quantity_used
FROM treatments;


# 11.Calculate average age of patients category-wise (Male / Female).

select gender, avg(age)
 from patients 
 group by gender;
 
 #  ADVANCED SQL QUESTIONS

# 12. Calculate disease-wise average length of stay (difference between admit_date and bill_date).

select p.disease,avg(datediff(p.admit_date,b.bill_date))
from bills b 
join  patients p using(patient_id)
group by p.disease;

# 13. Identify which specific medicine generated the highest revenue overall.
 
select m.medicine_name , sum(cost*quantity) as highest_revenue
from treatments t 
join medicines m using (medicine_id) 
group by medicine_name 
order by highest_revenue desc 
limit 1;

# 14. Find which day of week has highest number of admissions in the hospital.

select dayname(admit_date)as weekday ,count(*) as no_of_patients
from patients
group by weekday 
order by no_of_patients desc 
limit 1;

# 15.List top 3 patients with highest bill amount.

select p.patient_name , total_amount 
from bills b 
join patients p using (patient_id) 
group by patient_name,total_amount 
order by total_amount desc 
limit 3;    

# 16. Identify patients who got treatment from more than one doctor (Cross Consult cases).

select patient_name, count(distinct doctor_id) as total_doctors
from patients
group by patient_name having total_doctors>1;

# 17. Create a Stored Procedure which returns revenue of a specific department based on department_id input parameter.

delimiter //

CREATE PROCEDURE GetRevenue( in dept_id INT )

BEGIN
    select d.department_name, sum(b.total_amount)as total_revenue 
    from bills b 
    join patients p on b.patient_id= p.patient_id 
    join departments d on p.department_id=d.department_id 
    where d.department_id = dept_id 
    group by d.department_name ;
END //

delimiter ;

call GetRevenue(3);







